web/css/index
AdriandeCita/webdocs-ua pull request #1
Opened 2021-07-23 11:07 UTC by undead404

Feel free to criticize

2021-07-23 11:37 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<div>{{CSSRef}}</div>
тільки зараз зрозумів, що треба буде іще налаштувати інтерполяцію оцих штук...

2021-07-23 11:40 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +tags:
Отут уже потрібен глоссарій. Посібник? Чи довідник? Треба Ігоря сюди, але тегнути не можу, бо він інвайт не прийняв х)

2021-07-23 11:41 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p><strong>Каскадні таблиці стилів</strong> (<strong>CSS</strong>) -- мова <a
`--` використовується в оригіналі в якості тире? о_О

2021-07-23 11:45 UTC, AdriandeCita commented
О, маю перше загальне побажання до оформлення пулл-реквесту - треба прикріплювати посилання на оригінал, щоб можна було сам переклад перевірити. Треба буде десь додати це у відповідний док

2021-07-23 12:12 UTC, undead404 commented on files/uk/web/css/index.html
> +<p><strong>Каскадні таблиці стилів</strong> (<strong>CSS</strong>) -- мова <a
ні, це я дуже спати хотів, коли перекладав, забув поправити) Там в оригіналі немає ніяких тире

2021-07-23 12:33 UTC, AdriandeCita requested changes

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +    робить зліпок <a href="https://www.w3.org/TR/css/">найсвіжішого стабільного стану специфікації CSS</a>.</p>
снапшот також у глоссарій. Я не певен, наскільки 'зліпок' буде хорошим варіантом. Альтернативи: знімок, відбиток. Треба подумати)

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p>Our <a href="/uk/docs/Learn/CSS">Зона вивчення CSS</a> містить низку модулів, що навчають CSS з нуля, - попередні
'Our' пропустив

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +    <dd>CSS (каскадні таблиці стилів) використовуються для стилізації та верстки веб-сторінок - наприклад, для зміни
Бажано не використовувати дефіси замість тире

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        інших декоративних можливостей. Цей модуль дасть м‘який початок вашому шляху до майстерності в CSS у вигляді
краще замість 'можливостей' вжити щось на кшталт 'особливостей'. В оригіналі features

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        жирності, нахилу, відступу між рядками та між літерами, падіння тіней, та інших особливостей тексту. Ми
можливо просто тіней? 'падіння тіней' сюди трохи не в'яжеться :thinking:

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        жирності, нахилу, відступу між рядками та між літерами, падіння тіней, та інших особливостей тексту. Ми
сюди ж, думаю, замість 'особливостей' краще вжити 'властивостей'

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        коробками, в котрих вміщається контент. Тепер пора поглянути на те, як розташувати ці коробки у потрібному місці
думаю, краще замість коробок вжити блоки

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        відносно доступного простору і одне одного. Ми покрили необхідні передумови і можемо заглибитись у CSS верстку,
отут краще переформулювати речення, воно звучить трохи неоковирно

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/Containing_block">Ємний блок</a></li>
ємний блок... треба придумати щось ліпше, але поки на думку нічого не спадає

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +                    title="Стогувальний контекст">Стогувальний</a> та <a
те саме тут

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Flexible_Box_Layout">CSS верстка зручної коробки</a></li>
думаю, краще все-таки блок. Гнучкий блок? Еластичний блок? Треба подумати

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<h2 class="Tools" id="Cookbook">Шпаргалка</h2>
шпаргалка - це ж скоріше cheatsheet. Тут радше книга рецептів... Але теж трохи неоковирно. Є сенс придумати щось краще

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<h2 id="See_also">Також див.</h2>
'Дивіться також'?

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<h2 id="Meta_bugs">Meta bugs</h2>
цікаво, нам взагалі є потреба тримати цю секцію тут?

2021-07-23 12:33 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p>The <a href="/uk/docs/Web/CSS/Layout_cookbook">Шпаргалка CSS</a> прагне зібрати докупи рецепти загальноприйнятих
The пропущено

2021-07-23 12:42 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>Якщо ви новачок у веб-розробці, обов‘язково прочитайте нашу статтю <a
Веб пишемо без дефіса. веброзробка, вебдизайнер. Потрібно виправити скрізь.

2021-07-23 12:57 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    як елементи будуть відрендерені на екрані, папері, у мовленні чи в іншому вигляді.</p>
описує який вигляд матимуть елементи

2021-07-23 13:02 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизується між веб-бравзерами згідно <a
до основних мов? стандартизована для використання у браузерах (переглядачах) згідно зі специфікаціями W3C

2021-07-23 13:04 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        href="https://w3.org/Style/CSS/#specs">W3C специфікацій</a>. У минулому розробка різних частин CSS специфікації
різних частин специфікації CSS (поміняти слова місцями)

2021-07-23 14:25 UTC, undead404 commented on files/uk/web/css/index.html
> +<h2 id="Meta_bugs">Meta bugs</h2>
Думаю, не потрібно

2021-07-23 15:38 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<h2 id="Meta_bugs">Meta bugs</h2>
Для історії - це треба буде додати в гайдлайн

2021-07-23 19:07 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Flexible_Box_Layout">CSS верстка зручної коробки</a></li>
Гнучка розкладка блоків, о!

2021-07-23 21:12 UTC, Aenqau commented on files/uk/web/css/index.html
> +            валідації CSS від W3C</a>. Це незамінний інструмент зневадження.</li>
Це мабуть питання глосарію, але у нас "зневадження" чи "налагодженння"? Зневадження сюди підходить мабуть ліпше, але трішки ріже вухо. "Дебагінг" не пропоную

2021-07-23 21:13 UTC, Aenqau commented on files/uk/web/css/index.html
> +            валідації CSS від W3C</a>. Це незамінний інструмент зневадження.</li>
Я просто перший раз пропустив літеру "д" в слові х)

2021-07-23 22:41 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +tags:
Довідник https://e2u.org.ua/s?w=Reference&highlight=on

2021-07-24 00:24 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        href="/uk/docs/Web/XML/XML_introduction">XML</a> (включаючи діалекти XML на кшталт <a
Пропоную виключити з нашого стилю покруч «включаючи» та вживати «включно з діалектами». Цього слова не містить навіть ненависний усім СУМ http://sum.in.ua/s/vkljuchajuchy

2021-07-24 00:39 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    як елементи будуть відрендерені на екрані, папері, у мовленні чи в іншому вигляді.</p>
Проблема відображення, що воно відбиття, або віддзеркалення. Це слово має ту ж біду що й відмальовування. Тож пропоную замінювати його на «показано» або «зображено». Найпростіший обхід — «описує який вигляд матимуть елементи»

2021-07-24 00:46 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        рекомендації окремо в межах модулів</a>. Замість оформлення редакцій специфікації CSS, W3C тепер періодично
окремі рекомендації для кожного модуля.

2021-07-24 00:50 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    робить зліпок <a href="https://www.w3.org/TR/css/">найсвіжішого стабільного стану специфікації CSS</a>.</p>
Зі школи пам'ятаю контрольний зріз знань. Саме про це йдеться. Зрозумілість «зрізу» теж викликає питання.

2021-07-24 00:54 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>Якщо ви новачок у веб-розробці, обов‘язково прочитайте нашу статтю <a
«Нашу» пропоную прибрати.

2021-07-24 00:59 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            href="/uk/docs/Learn/Getting_started_with_the_web/CSS_basics">основи CSS</a>, аби дізнатися, що таке CSS та
«Аби» вживаємо у значені «Бодайбо йому сніг серед літа», «аби лиш не я». Тут доречно лише «щоб»

2021-07-24 01:01 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>Наша <a href="/uk/docs/Learn/CSS">зона вивчення CSS</a> містить силу силенну підручників, аби допомогти на шляху
аби

2021-07-24 01:04 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        від початкового рівня до майстерності, покриваючи усі засадничі принципи.</dd>
від початкового до високого рівня майстерності

2021-07-24 01:11 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <h4 id="Looking_to_become_a_front-end_web_developer">Бажаєте стати фронтенд веб-розробником?</h4>
Веб- тут зайве. Потрібно прибрати. фронтенд-розробником (правильним було б «розробником клієнтської частини», але тут такий пуризму зайвий).

2021-07-24 01:15 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<p>Our <a href="/uk/docs/Learn/CSS">Зона вивчення CSS</a> містить низку модулів, що навчають CSS з нуля, - попередні
І дефіс замість тире.

2021-07-24 01:17 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>CSS (каскадні таблиці стилів) використовуються для стилізації та верстки веб-сторінок - наприклад, для зміни
У цьому місці верстка (а насправді верстання) варто замінити на створення.

2021-07-24 01:20 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        шрифту, кольору, розміру, інтервалів вашого контенту, поділу його на кілька колонок, або додання анімацій та
Якщо це не архітектурна форма, то варто вжити «стовпчик». І чому «додання», а не «додавання»?

2021-07-24 01:35 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            тепер, маючи близьке знайомство із мовою та її синтаксисом, і отримавши деякий базовий досвід її
тепер, ознайомившись з основами мови та її синтаксисом

2021-07-24 01:38 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            використання, пора дещо заглибитись. Цей модуль звертає погляд на каскад та наслідування, всі доступні типи
Цей модуль розповідає (описує) про каскадність та наслідування

2021-07-24 01:41 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            селекторів, одиниці вимірювання, розміри, стилізацію тла та меж, і на багато іншого.</p>
меж, і на багато іншого — меж та багато іншого.

2021-07-24 01:42 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        <p>Його метою є надання набору інструментів для написання грамотного CSS та допомога у розумінні всієї суттєвої
у розумінні всієї суттєвої — у розумінні всієї необхідної

2021-07-24 01:44 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            теорії перед переходом до більш специфічних дисциплін штибу <a
штиб

2021-07-24 01:55 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS верстки</a>.</p>
Вибираємо щось звідси — https://e2u.org.ua/s?w=layout&dicts=all&main_only=on&highlight=on «створення макетів за допомогою CSS», «розміщення елементів за допомогою CSS», «компонування елементів за допомогою CSS», «розбивання елементів за допомогою CSS», «форматування сторінки за допомогою CSS».

2021-07-24 01:56 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS верстки</a>.</p>
Так, одним словом тут не вийде. Так, верстка (має бути верстання) не підійде.

2021-07-24 01:59 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>Після покриття основ мови CSS, наступною темою є стилізація тексту - одна з найбільш поширених справ, котрі
Після ознайомлення з основами. ТИРЕ

2021-07-24 02:02 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми поглянемо на засадничі основи стилізації тексту, включаючи встановлення шрифта,
Тут ми розглянемо; «засадничі» прибираємо, включаючи — включно з

2021-07-24 02:03 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        жирності, нахилу, відступу між рядками та між літерами, падіння тіней, та інших особливостей тексту. Ми
після тіней прибрати кому

2021-07-24 02:06 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        завершуємо модуль поглядом на встановлення власних шрифтів на вашу сторінку, і стилізацію списків та посилань.
поглядом — оглядом застосування власних шрифтів для вашої сторінки та стилізації списків і посилань.

2021-07-24 02:07 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dt><a href="/uk/docs/Learn/CSS/CSS_layout">CSS верстка</a></dt>
Верстка

2021-07-24 02:09 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>В цій точці шляху засади CSS уже пройдені, ви уже знаєте, як стилізувати текст і як стилізувати і маніпулювати
ви вже; після текст додати кому; стилізувати й маніпулювати

2021-07-24 02:10 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        коробками, в котрих вміщається контент. Тепер пора поглянути на те, як розташувати ці коробки у потрібному місці
блоками з вмістом.

2021-07-24 02:14 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        відносно доступного простору і одне одного. Ми покрили необхідні передумови і можемо заглибитись у CSS верстку,
як розташувати ці блоки на сторінці та відносно одне одного.

2021-07-24 02:15 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        відносно доступного простору і одне одного. Ми покрили необхідні передумови і можемо заглибитись у CSS верстку,
верстку замінити

2021-07-24 02:18 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        поглянути на різні налаштування екранів, сучасні інструменти верстки штибу flexbox, CSS grid та позиціонування,
сучасні інструменти створення сторінок, як-от; позиціонування — позиціювання

2021-07-24 02:21 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dt><a href="/uk/docs/Learn/CSS/Howto">Використовуйте CSS для вирішення поширених проблем</a></dt>
вирішення поширених проблем — розв'язання, подолання, усунення

2021-07-24 02:22 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>Цей модуль надає посилання на секції контенту, що пояснює, як використовувати CSS для вирішення поширених
Модуль містить посилання на розділи з поясненнями як користуватися CSS для усунення

2021-07-24 02:23 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        проблем під час створення веб-сторінки.</dd>
вебсторінки.

2021-07-24 02:25 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                    href="/uk/docs/Web/CSS/Cascade">каскад</a></li>
каскадність

2021-07-24 02:27 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Values_and_Units">Одиниці вимірювання та значення CSS</a> та <a
вимірювання і значення

2021-07-24 02:29 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model">Коробкова модель</a> та <a
Блокова модель

2021-07-24 02:32 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                    href="/uk/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing">згортання полів</a></li>
перекриття зовнішніх відступів

2021-07-24 02:36 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/Containing_block">Ємний блок</a></li>
Блок із вмістом (для вмісту). Треба мізкувати.

2021-07-24 02:39 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                    title="Стогувальний контекст">Стогувальний</a> та <a
Контекст накладення

2021-07-24 02:44 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Flexible_Box_Layout">CSS верстка зручної коробки</a></li>
Розкладка блоків за допомогою Flex (або блоків флекс). Це принцип за назвою властивості, тож дайте йому спокій і не перекладайте.

2021-07-24 02:50 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Flexible_Box_Layout">CSS верстка зручної коробки</a></li>
Але я б взагалі не перекладав цю назву.

2021-07-24 02:51 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Grid_Layout">Сіткова верстка CSS</a></li>
Аналогічно — Розташування елементів за допомогою ґ(г)рід.
Знов же, я б не перекладав цього.

2021-07-24 02:52 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Selectors">CSS селектори</a></li>
Або Селектори CSS, або CSS-селектори

2021-07-24 02:55 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<h2 class="Tools" id="Cookbook">Шпаргалка</h2>
Тут точно треба витлумачити інакше

2021-07-24 02:56 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    шаблонів верстки, речей, котрі можуть бути потрібними при реалізаці
верстка — створення сторінок

2021-07-24 03:01 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    показують різні способи застосування специфікацій верстки, і рішень, котрі можуть бути прийняті розробником.</p>
специфікацій для створення макетів

2021-07-24 03:02 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<h2 class="Tools" id="Tools_for_CSS_development">Інструменти CSS розробки</h2>
CSS-розробки

2021-07-24 03:04 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <li>Для перевірки валідності власного CSS можна застосовувати <a href="https://jigsaw.w3.org/css-validator/">Сервіс
Власного прибрати, код можна й чужий перевірити. Службу перевірки CSS від W3C

2021-07-24 03:06 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            веб-розробника</a> для Firefox дає змогу відстежувати та редагувати на льоту CSS на відображених веб-сайтах.
веброзробника

2021-07-24 03:08 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<h2 id="See_also">Також див.</h2>
Перегляньте, читайте

2021-07-25 07:14 UTC, undead404 commented on files/uk/web/css/index.html
> +<div>{{CSSRef}}</div>
Я тут геть не зрозумів, що має бути, тому лишив як є

2021-07-25 07:20 UTC, undead404 commented on files/uk/web/css/index.html
> +    <dd>CSS (каскадні таблиці стилів) використовуються для стилізації та верстки веб-сторінок - наприклад, для зміни
Якщо в оригіналі to layout, то, можливо, краще писати "верстання" для прямоти перекладу?

2021-07-25 07:29 UTC, undead404 commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Flexible_Box_Layout">CSS верстка зручної коробки</a></li>
Я не згоден, якщо flex - то можна лишити, а якщо flexible - то треба або повністю перекласти, або зробити словотвір типу "флексова"

2021-07-25 07:30 UTC, undead404 commented on files/uk/web/css/index.html
> +<h2 id="Meta_bugs">Meta bugs</h2>
То треба прибирати чи ні?

2021-07-25 07:34 UTC, undead404 commented on files/uk/web/css/index.html
> +            валідації CSS від W3C</a>. Це незамінний інструмент зневадження.</li>
Ну налагодження то не то. Хай буде зневадження

2021-07-25 07:39 UTC, undead404 commented on files/uk/web/css/index.html
> +    <dd>Якщо ви новачок у веб-розробці, обов‘язково прочитайте нашу статтю <a
А там, де "наша" перед всякими розділами документації - лишати чи най буде?

2021-07-25 07:41 UTC, undead404 commented on files/uk/web/css/index.html
> +        шрифту, кольору, розміру, інтервалів вашого контенту, поділу його на кілька колонок, або додання анімацій та
Лишу питання без відповіді))

2021-07-25 07:42 UTC, undead404 commented on files/uk/web/css/index.html
> +            тепер, маючи близьке знайомство із мовою та її синтаксисом, і отримавши деякий базовий досвід її
В оригіналі немає нічого про "основи" в цьому місці, пропоную замінити без цього слова

2021-07-25 07:44 UTC, undead404 commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS верстки</a>.</p>
По-моєму, "компонування" передає суть

2021-07-25 07:47 UTC, undead404 commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS верстки</a>.</p>
Сайт цей лежить, здається

2021-07-25 08:00 UTC, undead404 commented on files/uk/web/css/index.html
> +tags:
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:00 UTC, undead404 commented on files/uk/web/css/index.html
> +<p><strong>Каскадні таблиці стилів</strong> (<strong>CSS</strong>) -- мова <a
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:00 UTC, undead404 commented on files/uk/web/css/index.html
> +    як елементи будуть відрендерені на екрані, папері, у мовленні чи в іншому вигляді.</p>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:01 UTC, undead404 commented on files/uk/web/css/index.html
> +<p>Починаючи від CSS3, обсяг специфікації помітно зростав, і прогрес різних модулів CSS почав настільки сильно
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:01 UTC, undead404 commented on files/uk/web/css/index.html
> +    робить зліпок <a href="https://www.w3.org/TR/css/">найсвіжішого стабільного стану специфікації CSS</a>.</p>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:01 UTC, undead404 commented on files/uk/web/css/index.html
> +<p>Our <a href="/uk/docs/Learn/CSS">Зона вивчення CSS</a> містить низку модулів, що навчають CSS з нуля, - попередні
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:01 UTC, undead404 commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Flexible_Box_Layout">CSS верстка зручної коробки</a></li>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:01 UTC, undead404 commented on files/uk/web/css/index.html
> +<h2 class="Tools" id="Cookbook">Шпаргалка</h2>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:01 UTC, undead404 commented on files/uk/web/css/index.html
> +<h2 id="See_also">Також див.</h2>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:01 UTC, undead404 commented on files/uk/web/css/index.html
> +<p>The <a href="/uk/docs/Web/CSS/Layout_cookbook">Шпаргалка CSS</a> прагне зібрати докупи рецепти загальноприйнятих
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:02 UTC, undead404 commented on files/uk/web/css/index.html
> +    <dd>Якщо ви новачок у веб-розробці, обов‘язково прочитайте нашу статтю <a
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

Правда, з‘явились штуки виду "вебспільнота", "вебмови"

2021-07-25 08:02 UTC, undead404 commented on files/uk/web/css/index.html
> +    як елементи будуть відрендерені на екрані, папері, у мовленні чи в іншому вигляді.</p>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:02 UTC, undead404 commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизується між веб-бравзерами згідно <a
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:02 UTC, undead404 commented on files/uk/web/css/index.html
> +        href="https://w3.org/Style/CSS/#specs">W3C специфікацій</a>. У минулому розробка різних частин CSS специфікації
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:02 UTC, undead404 commented on files/uk/web/css/index.html
> +        href="/uk/docs/Web/XML/XML_introduction">XML</a> (включаючи діалекти XML на кшталт <a
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:02 UTC, undead404 commented on files/uk/web/css/index.html
> +        рекомендації окремо в межах модулів</a>. Замість оформлення редакцій специфікації CSS, W3C тепер періодично
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:02 UTC, undead404 commented on files/uk/web/css/index.html
> +            href="/uk/docs/Learn/Getting_started_with_the_web/CSS_basics">основи CSS</a>, аби дізнатися, що таке CSS та
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +    <dd>Наша <a href="/uk/docs/Learn/CSS">зона вивчення CSS</a> містить силу силенну підручників, аби допомогти на шляху
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +        від початкового рівня до майстерності, покриваючи усі засадничі принципи.</dd>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +    <h4 id="Looking_to_become_a_front-end_web_developer">Бажаєте стати фронтенд веб-розробником?</h4>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +        шрифту, кольору, розміру, інтервалів вашого контенту, поділу його на кілька колонок, або додання анімацій та
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +            тепер, маючи близьке знайомство із мовою та її синтаксисом, і отримавши деякий базовий досвід її
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +            використання, пора дещо заглибитись. Цей модуль звертає погляд на каскад та наслідування, всі доступні типи
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +            селекторів, одиниці вимірювання, розміри, стилізацію тла та меж, і на багато іншого.</p>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +        <p>Його метою є надання набору інструментів для написання грамотного CSS та допомога у розумінні всієї суттєвої
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +            теорії перед переходом до більш специфічних дисциплін штибу <a
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:03 UTC, undead404 commented on files/uk/web/css/index.html
> +    <dd>Після покриття основ мови CSS, наступною темою є стилізація тексту - одна з найбільш поширених справ, котрі
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:04 UTC, undead404 commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми поглянемо на засадничі основи стилізації тексту, включаючи встановлення шрифта,
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:04 UTC, undead404 commented on files/uk/web/css/index.html
> +        завершуємо модуль поглядом на встановлення власних шрифтів на вашу сторінку, і стилізацію списків та посилань.
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:04 UTC, undead404 commented on files/uk/web/css/index.html
> +    <dd>В цій точці шляху засади CSS уже пройдені, ви уже знаєте, як стилізувати текст і як стилізувати і маніпулювати
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:04 UTC, undead404 commented on files/uk/web/css/index.html
> +        поглянути на різні налаштування екранів, сучасні інструменти верстки штибу flexbox, CSS grid та позиціонування,
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +        поглянути на різні налаштування екранів, сучасні інструменти верстки штибу flexbox, CSS grid та позиціонування,
Тільки от "створення сторінок" - я не згодний, розробка, реалізація, створення - це різне

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +    <dt><a href="/uk/docs/Learn/CSS/Howto">Використовуйте CSS для вирішення поширених проблем</a></dt>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +    <dd>Цей модуль надає посилання на секції контенту, що пояснює, як використовувати CSS для вирішення поширених
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +        проблем під час створення веб-сторінки.</dd>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +                    href="/uk/docs/Web/CSS/Cascade">каскад</a></li>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Values_and_Units">Одиниці вимірювання та значення CSS</a> та <a
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model">Коробкова модель</a> та <a
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +                    href="/uk/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing">згортання полів</a></li>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Grid_Layout">Сіткова верстка CSS</a></li>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:05 UTC, undead404 commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Selectors">CSS селектори</a></li>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:06 UTC, undead404 commented on files/uk/web/css/index.html
> +    шаблонів верстки, речей, котрі можуть бути потрібними при реалізаці
Написання коду і компонування - це різне. Решту поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:07 UTC, undead404 commented on files/uk/web/css/index.html
> +    показують різні способи застосування специфікацій верстки, і рішень, котрі можуть бути прийняті розробником.</p>
"To layout" це "створювати макет"? Перепитую

2021-07-25 08:07 UTC, undead404 commented on files/uk/web/css/index.html
> +<h2 class="Tools" id="Tools_for_CSS_development">Інструменти CSS розробки</h2>
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:07 UTC, undead404 commented on files/uk/web/css/index.html
> +    <li>Для перевірки валідності власного CSS можна застосовувати <a href="https://jigsaw.w3.org/css-validator/">Сервіс
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 08:07 UTC, undead404 commented on files/uk/web/css/index.html
> +            веб-розробника</a> для Firefox дає змогу відстежувати та редагувати на льоту CSS на відображених веб-сайтах.
Поправив. https://github.com/AdriandeCita/webdocs-ua/pull/1/commits/9c474ab9b98f7791d1a58cb1b93f386a7e6019f9

2021-07-25 09:55 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<div>{{CSSRef}}</div>
тут нічого не має бути, просто думки вголос. Вибачаюсь, що збив з пантелику

2021-07-25 09:58 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<h2 id="Meta_bugs">Meta bugs</h2>
Прибираємо. Проглянув три різні локалізації цієї сторінки на мдн - жодна не має цієї секції

2021-07-25 10:04 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
з — зі

2021-07-25 10:06 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        href="https://w3.org/Style/CSS/#specs">W3C специфікаціями</a>. У минулому розробка різних частин специфікації CSS
W3C специфікаціями — специфікаціями W3C

2021-07-25 10:08 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +    робить зліпок <a href="https://www.w3.org/TR/css/">найсвіжішого стабільного стану специфікації CSS</a>.</p>
Для історії - в чаті мали розмову з приводу перекладання "снапшоту" словами "зріз" чи "знімок". Обидва варіанти хороші доти, доки ми зберігаємо семантику:
- Зріз зазвичай використовується в контексті роботи з масивами і колекціями, в якості позначення процесу вибірки підмножини елементів із більшої колекції.
- Snapshot - зазвичай означає створення миттєвої копії, збереження інформації про стан системи у окремо взятий момент часу. "Знімок" звучить неідеально, але більш підходяще для опису саме миттєвої копії

2021-07-25 10:14 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a>.</p>
CSS-компонування

2021-07-25 10:15 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Flexible_Box_Layout">CSS верстка зручної коробки</a></li>
думаю, для початку ок. Загалом підтримую @undead404 у тому плані, що це не просто флексбокс. Це назва специфікації W3C: CSS Flexible Box Layout (see it here https://www.w3.org/TR/css-flexbox-1/). Рано чи пізно нам треба буде перекласти цей вираз

2021-07-25 10:18 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a>.</p>
Але чи правильне таке подання? Виходить компонування самого CSS, а нам потрібно компонувати елементи сторінки за допомогою CSS. Пропоную «компонування (елементів) сторінки за допомогою CSS»

2021-07-25 10:20 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми розглянемо основи стилізації тексту, включно з встановленням шрифта,
не додивився, сам неправильно запропонував) «з» замінити на «зі»

2021-07-25 10:22 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dt><a href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a></dt>
CSS-компонування

2021-07-25 10:26 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +    <dd>Якщо ви новачок у веб-розробці, обов‘язково прочитайте нашу статтю <a
та краще лишай. Не ми автори цього контенту, і навряд чи та стаття буде доступна українською на момент публікації цього тексту, але й явну атрибуцію ми також додамо. Не будемо тратити більше зусиль, ніж потрібно.
Плюс, якщо в перспективі ми таки вернемося в лоно МДН, то треба буде повертати "Нашу" на місце? Я б не хотів створювати для майбутнього себе стільки роботи

2021-07-25 10:26 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        блоками, в котрих вміщається контент. Тепер пора поглянути на те, як розташувати ці блоки на сторінці і відносно
сторінці і — сторінці й або та

2021-07-25 10:34 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Flexible_Box_Layout">CSS flex-компонування</a></li>
Flex-компонування у CSS

2021-07-25 10:34 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Grid_Layout">CSS grid-компонування</a></li>
Grid-компонування у CSS

2021-07-25 10:36 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    шаблонів компонування та іншого, що може знадобитись при розробці
при — під час

2021-07-25 10:37 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS верстки</a>.</p>
компонування передає суть процесу, але верстка - це уже усталений термін, в першу чергу в поліграфії/типографії, звідки він і прийшов. Мені не дуже подобається, що він звучить так само як і російською, але думаю, тут у нас варіантів небагато.
Так, в перекладі слова "layout" верстки немає, але зворотній переклад верстки дає якраз "layout" :thinking:

2021-07-25 10:41 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>Якщо ви новачок у веб-розробці, обов‘язково прочитайте нашу статтю <a
Згоден.

2021-07-25 10:44 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        поглянути на різні налаштування екранів, сучасні інструменти верстки штибу flexbox, CSS grid та позиціонування,
Продовжу тут. Компонування - це дуже загальний термін. Якщо ми все-таки пристаємо до терміну "компонування", то давайте уточнювати "...інструменти компонування елементів, як-от: flexbox, CSS grid та позиціювання...".

2021-07-25 10:45 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +            селекторів, одиниці вимірювання, розміри, стилізацію тла та меж та багато іншого.</p>
Не додивився, сполучник «та» повторюється. «меж та багато» — «меж і багато»

2021-07-25 10:45 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        поглянути на різні налаштування екранів, сучасні інструменти верстки штибу flexbox, CSS grid та позиціонування,
плюс, якщо я вірно пам'ятаю, перед переліком треба вставляти двокрапку

2021-07-25 10:46 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/CSS_Grid_Layout">Сіткова верстка CSS</a></li>
те саме. Це назва специфікації. Наразі ок, але нам треба буде повернутись до цього питання https://www.w3.org/TR/css-grid-1/

2021-07-25 10:50 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +    показують різні способи застосування специфікацій верстки, і рішень, котрі можуть бути прийняті розробником.</p>
у нас проблема з макетами, тому що цей термін закріплений за дизайном. Там, де у англомовних спеціалістів "designs, mockups" - у нас макети; де у них "layout" (макет) - у нас верстка. Я б не використовував тут макети взагалі, оскільки перша асоціація з макетами у сфері розробки - це відповідне зображення у фотошопі, а не код

2021-07-25 10:51 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
до речі, languageTool, здається, має відслідковувати такі штуки, хіба ні?

2021-07-25 10:53 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
Саме тому пропоную зробити його застосування обов'язковим перед надсиланням перекладу.

2021-07-25 11:09 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +            <li><a href="/uk/docs/Web/CSS/Containing_block">Ємний блок</a></li>
Я хотів тут написати щось розумне, але у мене з'явилася інша ідея. Давайте зупинимося на тому що є, а обговорення далі перенесемо в Issues.

Для історії збережу чорновик коментаря, потім перенесу його в обговорення.
> Давайте подумаємо. Тут мається на увазі зона вмісту блоку https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block. Це місце, яке буде займати блок на макеті зображеної сторінки, залежно від параметрів рамки, власне розмірів, внутрішніх і зовнішніх полів. При цьому, ми не можемо використовувати термін "зона вмісту", бо у блока є своя content area.

2021-07-25 11:10 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +                    title="Стогувальний контекст">Стогувальний</a> та <a
Думаю, для початку це звучить достатньо непогано. Давайте поки зупинимося на цьому

2021-07-25 11:12 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
Всіма руками за, але через хтмл це трохи незручно. Треба буде:
- Описати цей момент у наших настановах
- Придумати, як його зробити простішим для перекладачів, щоб не гратися з конвертацією коду в текст, і назад

2021-07-25 11:13 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a>.</p>
тоді вже "верстання сторінки...", щоб не роздувати текст

2021-07-25 11:14 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a>.</p>
дідько... комент невалідний :point_up:, бо "верстання сторінки за допомогою CSS" взагалі ні разу не компактніше

2021-07-25 11:17 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a>.</p>
Верстання за допомогою CSS. Найстисліше, що спадає на думку

2021-07-25 11:21 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    мовою<a href="/uk/docs/Web/HTML" title="Мова розмітки гіпертексту">HTML</a> або <a
після «мовою» додати пробіл

2021-07-25 11:23 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
@AdriandeCita він чудово розуміє HTML, нічого не потрібно перекомпоновувати moz-extension://5e3a7a84-ca35-4d17-99f0-f66b040b3934/validator/validator.html

2021-07-25 11:25 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dd>Наша <a href="/uk/docs/Learn/CSS">зона вивчення CSS</a> містить силу силенну підручників, щоб допомогти на шляху
силу-силенну — через дефіс

2021-07-25 11:46 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a>.</p>
так, але це вже звучить як тавтологія. CSS і так тільки для верстання й використовується

2021-07-25 11:53 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
здається, так, але треба принаймні прибирати переноси з коду

2021-07-25 11:56 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
"...згідно зі W3C специфікаціями"? Там точно має бути зі @IhorHordiichuk ?

2021-07-25 11:57 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
LanguageTool не бачить жодних проблем, тож я б краще залишив як є
![image](https://user-images.githubusercontent.com/11510394/126898130-3b3de1da-baa6-4282-bbec-a74ef5b8f91f.png)

2021-07-25 11:58 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми розглянемо основи стилізації тексту, включно з встановленням шрифта,
те саме тут. Мені здається, "з" сюди вписується значно краще

2021-07-25 12:00 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
@AdriandeCita згідно зі специфікаціями W3C — слова потрібно поміняти місцями. LT nfrb[ gjvbkjr yt ,fxbnm

2021-07-25 12:02 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми розглянемо основи стилізації тексту, включно з встановленням шрифта,
@AdriandeCita прочитай вголос обидва варіанти, це найкращий спосіб перевірки «чому так»

2021-07-25 12:03 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
@IhorHordiichuk я не про зміну порядку слів, а заміну з-зі

2021-07-25 12:05 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +<p>CSS належить до ключових мов <strong>відкритого вебу</strong> і стандартизована між вебпереглядачами згідно з <a
@AdriandeCita ці слова треба поміняти місцями (наступний коментар) тому тут «зі»

2021-07-25 12:07 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми розглянемо основи стилізації тексту, включно з встановленням шрифта,
ноуп, не допомогло. Може ти мав на увазі не "зі", а "із"?
"включно ІЗ встановленням..."

2021-07-25 12:11 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        href="https://w3.org/Style/CSS/#specs">W3C специфікаціями</a>. У минулому розробка різних частин специфікації CSS
так, так звучить краще

2021-07-25 12:16 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми розглянемо основи стилізації тексту, включно з встановленням шрифта,
«включно із встановленням шрифту» — збіг двох приголосних і чотирьох голосних, але я зрозумів у чому проблема —  має бути «включно з установленням шрифту»

2021-07-25 12:18 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a>.</p>
Може просто верстання?

2021-07-25 12:28 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +                href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a>.</p>
Я вже й сам заплутався, пропоную зупинитися на CSS-верстання та й по всьому.

2021-07-25 12:34 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми розглянемо основи стилізації тексту, включно з встановленням шрифта,
ммм, от що ти мав на увазі... Ок, аргумент приймається, я просто практично не зустрічав такий паттерн, тому воно мені зараз трохи ріже вуха.

2021-07-25 12:43 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми розглянемо основи стилізації тексту, включно з встановленням шрифта,
у нас таке розмаїття у, в, з, із, зі, зо, тож не дивно, але правила існують, і я теж за них забув https://web.posibnyky.vntu.edu.ua/icgn/radomska_ukr_mova/3.htm

2021-07-25 12:47 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +        доводиться робити на CSS. Тут ми розглянемо основи стилізації тексту, включно з встановленням шрифта,
І у-в, найдокладніше пояснення, вони взяли з посібника  — https://zbruc.eu/node/41947

2021-07-25 12:49 UTC, AdriandeCita commented on files/uk/web/css/index.html
> +    <dt><a href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a></dt>
тоді тут ми також приходимо до верстки або верстання.

2021-07-25 12:50 UTC, IhorHordiichuk commented on files/uk/web/css/index.html
> +    <dt><a href="/uk/docs/Learn/CSS/CSS_layout">CSS компонування</a></dt>
Так

2021-07-30 12:52 UTC, undead404 commented
Moved to https://github.com/webdoky/content/pull/2

2021-07-30 12:52 UTC, closed without merging